### ISSUE TITLE
[fix]: CDATA is not parsed

### ISSUE THREAD

**Issue by RReverser** [posthtml/posthtml-parser#11]
This claims to be both HTML and XHTML parser, however CDATA in XML would be parsed as it's inner content, while currently it's left untouched. This leads to cases where e.g.:

``` html
<script><![CDATA[console.log(1);]]></script>
```

results in an invalid JavaScript syntax, despite being correctly understood in XHTML context.

**Comment by jescalan** [comment]
This should be fixable, htmlparser2 does parse and recognize CDATA. We might just have to pass an additional option:

https://github.com/fb55/htmlparser2/wiki/Parser-options#option-recognizecdata

**Comment by GitScrum** [comment]
@RReverser Hi, this is actual ?
If you use `xmlMode: true` in `posthtml` options will be good.

```js
posthtml(plugins, {
      xmlMode: true
})
```

you get AST

```js
[{
    tag: 'script',
    content: ['console.log(1);']
}]
```

**Comment by GitScrum** [comment]
@RReverser ping ?

**Comment by RReverser** [comment]
Yes, from your example looks like it's fixed now, thanks.
