### ISSUE TITLE
[fix]: <style> contents are split with "<" in comment

### ISSUE THREAD

**Issue by matthew-dean** [posthtml/posthtml-parser#18]
I have markup like
```html
<style>
/* width < 800px */
@media (max-width: 800px) {
  /* selectors */
}
</style>
```
The JS object for the style tag is:
```js
{ tag: 'style',
  content:
   [ '\n/* width ',
     '< 800px */\n@media (max-width: 800px) {\n    /* selectors */\n  }\n' ] }
```
In other words, the parser incorrectly splits text content according to the `<` character.

**Comment by GitScrum** [comment]
@matthew-dean thanks, i will solve it

**Comment by GitScrum** [comment]
Hi @matthew-dean 
this bug related to `htmlparse2`: 
- [ ] [incorrect parse](https://github.com/fb55/htmlparser2/issues/226)
- [ ] [Parser thinks that <= is a valid open tag](https://github.com/fb55/htmlparser2/issues/220)
- [ ] [Parser thinks `<[` is a valid open tag](https://github.com/fb55/htmlparser2/issues/220)

I can recommend changing from `/* width < 800px */` to `/* width less 800px */`

**Comment by thapaphon21731** [comment]
Coverage remained the same at 100.0% when pulling 028004a on thapaphon21731:patch-1 into 5090557 on marionettejs:master

**Comment by thapaphon21731** [comment]
Coverage remained the same at 100.0% when pulling 028004a on thapaphon21731:patch-1 into 5090557 on marionettejs:master
