### ISSUE TITLE
parse5

### ISSUE THREAD

**Issue by thisconnect** [posthtml/posthtml-parser#2]
Hi, have you considered parse5 it is used by jsdom and comes with a htmlparser2 treeadapter
https://github.com/inikulin/parse5/wiki/Documentation#parse5treeadapters

**Comment by stevenvachon** [comment]
+1

**Comment by devinus** [comment]
I came here just to create this issue.

**Comment by elbuo8** [comment]
:+1: :dancers:

**Comment by stevenvachon** [comment]
If it were to parse to the same data structure—as to provide as little breaking changes as possible—it would need a custom tree adaptor.

sax should probably be used to parse xml, but htmlparser2 could still be used. Either way, because parse5 does not parse xml documents (though, it will parse svg embedded within html), there will need to be two functions: `parseHtml` and `parseXml` -- so the API will change slightly.

**Comment by stevenvachon** [comment]
We should probably support both strings and streams, which should bring us to a promise-based API as well.

**Comment by voischev** [comment]
look at this issue https://github.com/posthtml/posthtml/issues/101#issuecomment-177917921

**Comment by stevenvachon** [comment]
A regex-based IE® conditional comment parser could be written to assist parse5 in getting more data (see #9).

**Comment by stevenvachon** [comment]
Now that v0.9 introduced the `options.parser`, is there still an interest in swapping out htmlparser2 for parse5? I still think that the default should be true HTML, which is spec-compliant -- htmlparser2 is only *pseudo*-HTML.

**Comment by michael-ciniawsky** [comment]
in progress :) 

[Parser](https://github.com/static-dev/posthtml-parser2) using parse5 as the default parser
[Core #159](https://github.com/posthtml/posthtml/pull/159)

**Comment by stevenvachon** [comment]
Awesome, thanks!

**Comment by jescalan** [comment]
This is the proposed final parser if anyone has thoughts: https://github.com/static-dev/posthtml-parser2/pull/2

**Comment by stevenvachon** [comment]
As a result of @jescalan's PR getting rejected, I'm getting the feeling that this project will lay dormant for a long while until randomly receiving a `1.0` stamp, just like Grunt did. A [custom spec-compliant parser](https://github.com/posthtml/posthtml/issues/163) will take too long to write.

**Comment by jescalan** [comment]
If you want to use the results of my PR immediately, you can use it through [reshape](https://github.com/reshape/reshape). It's already being used in production at a few projects at my company and is working well. Will see a public release in the next month or so. The parser [can be seen here](https://github.com/reshape/parser), it uses parse5's SAXParser as discussed.

I can't speak to whether this assumption about posthtml is accurate, but if I had to guess I would tend to agree with you here. There hasn't been much if any progress made in the last couple months, and as you said writing a custom parser is a not really necessary and also too ambitious.

**Comment by michael-ciniawsky** [comment]
The 'problem' on the root is the limitation of the current AST, it's simply impossible to progressively enhance it. The PostHTML interface itself should be as flexible as possible e.g use htmlparser2, parse5, whatever, interchangeably up to the taste of the user and his/her's usecase, while the AST Format must be agreed upon, the parser to generate it is not important.

long-term, of course there should be a parser developed here and acting as the default...it's AST, and thats the important thing, will be the baseline for all other possible implementations.

There is already progress and the time it takes, it simply takes :) 
[AST](https://gist.github.com/voischev/767c2822b6fe12f1ac608aba2b1cc888)

```js
import parse5 from 'posthtml-parse5' // posthtml-pug, posthtml-hbs, posthtml-parser2, posthtml-parser(PostHTML's own HTML Parser)
import jsx from 'posthtml-jsx' // posthtml-js, posthtml-render

posthtml(plugins)
  .process('file.html', { parser: parse5, render: jsx }).... // etc...
  .then((result) =>{
      result.html // with/without stringifier (e.g to js/jsx)
      result.tree //  with/without generator
   })
```

**Comment by stevenvachon** [comment]
@michael-ciniawsky that wasn't the problem though. The argument was that the AST cannot change because "we have users".

**Comment by michael-ciniawsky** [comment]
@stevenvachon yeah well... :), this discussion...i would give it a go, the gist above is from one core maintainers and i believe there will be some progress, if not or with tooooo much time without even the indication of progress, the so called 'market' will simply move on to other solutions if they are 'superior'.

**Comment by stevenvachon** [comment]
@michael-ciniawsky and you want people to move on from your hard work?

**Comment by michael-ciniawsky** [comment]
@stevenvachon Yeah no... 😛 I was in the 'find a compromise' camp from the beginning, but I can't do anything in this regard. I would have a few updates upon my sleeve which are blocked for a while now. A 'unification' effort and progress would make the most sense from a sole projects standpoint but  I'm not blocking nor able to do something about it ¯\_(ツ)_/¯

**Comment by stevenvachon** [comment]
What is blocking them? I don't see any work being done to unblock anything.

**Comment by jescalan** [comment]
Hi, just want to pop in and clarify that nobody has ever reached out to me about any "unification effort", nor have I ever been opposed to it (which is why the features that turned into reshape started out as a PR to posthtml), so I hope it's not being implied that I am the cause of anything being "blocked/"

I am entirely open any type of unification effort, so long as it does not end in a sacrifice of any of reshape's features, code quality, or test coverage. I'm available and happy to talk at any time.

✨ 💖 ✨

**Comment by stevenvachon** [comment]
cheerio 1.0.0-rc1 now uses parse5 by default.

**Comment by stevenvachon** [comment]
I still think it's important to be spec compliant.
