### ISSUE TITLE
[feat]: Ignore non-HTML tag

### ISSUE THREAD

**Issue by okyantoro** [posthtml/posthtml-parser#26]
In my use case, I have an HTML file which contains an EJS tag.
The current behavior of the API assume that everything started with ```<``` and closed with ```>``` is a tag. The problem is whenever we try to parse EJS tag, the library treat it as a tag. So, for example <%=title %>, the output will produce:

```
{
"tag":"'%=title"
...
}
```

Whenever we try to render back to HTML, the result will be something like ```<%=title></%=title>```.
Is there any option to ignore certain tags?
Thank you

**Comment by GitScrum** [comment]
@okyantoro Hi, you need use [directives](https://github.com/posthtml/posthtml-parser#directives), [example](https://github.com/posthtml/posthtml-parser/blob/master/test/test.js#L126-L150)

**Comment by okyantoro** [comment]
hello, @GitScrum thank you for your response. Yes, directives can do for specific tag name, but for EJS I think we need regex directive. So, I think it is useful if we have something like:
```
[{
    name: /%=?.\w*/,
    start: '<', 
    end: '>'
}]
```

**Comment by GitScrum** [comment]
@okyantoro Good idea

**Comment by GitScrum** [comment]
@okyantoro mey be this is help you https://github.com/posthtml/posthtml-render/pull/13 ?

**Comment by okyantoro** [comment]
@GitScrum thank you for pointing this out

**Comment by GitScrum** [comment]
@okyantoro close this issue ?

**Comment by okyantoro** [comment]
I'll close this issue @GitScrum
