### ISSUE TITLE
[feat]: set options

### ISSUE THREAD

**Issue by voischev** [posthtml/posthtml-parser#3]
Parse custom single tags. Look at https://github.com/posthtml/posthtml/issues/95

**Comment by GitScrum** [comment]
@voischev if use in options `xmlMode: true` and use notation `<cutom-tag />` will be good.
Not need more options.

**Comment by GitScrum** [comment]
but need add param for render )

**Comment by GitScrum** [comment]
but need param for `render`

**Comment by GitScrum** [comment]
Not need because single tag not have content
