### ISSUE TITLE
[bug]: attributes seperated with non-breakable space not parsed properly

### ISSUE THREAD

**Issue by chimurai** [posthtml/posthtml-parser#40]
A non-breakable space between attributes results in incorrect parsing:

```html
<h1 tests foo="bar">My First Heading</h1>
         ^--- non breakable space
```

current:
```json
{
  "nodeName": "h1",
  "tagName": "h1",
  "attrs": [
    {
      "name": "tests foo",
      "value": "bar"
    }
  ]
}

```

expected:
```json
{
  "nodeName": "h1",
  "tagName": "h1",
  "attrs": [
    {
      "name": "tests",
      "value": ""
    },
    {
      "name": "foo",
      "value": "bar"
    }
  ]
}

```

View AST online:
https://astexplorer.net/#/gist/d13142c629efe70f7b96ca3ff980890e/4144351744cd1a0bf747792a7f4e8fa18e6be0db

non breakable space: https://en.wikipedia.org/wiki/Non-breaking_space
mac: alt + shift + space

copy pasting from online documentation might introduce the nbsp; i.e. stackoverflow

**Comment by anikethsaha** [comment]
Seems like an issue with `htmlparser2` !!

cc @Scrum

**Comment by chimurai** [comment]
Didn't know posthtml-parser uses `htmlparser2` :D

AST with `htmlparser2`

```html
<h1 tests foo="bar">My First Heading</h1>
```

```json
{
  "type": "tag",
  "name": "h1",
  "attribs": {
    "tests foo": "bar"
  }
}
```

Link to online AST with `htmlparser2`:

https://astexplorer.net/#/gist/d13142c629efe70f7b96ca3ff980890e/cf631a5987db518147e5d31687499701060db8d0

**Comment by anikethsaha** [comment]
yes, its an issue with `htmlparser2`. 

Can you open an issue in that repo ?


Also, if you want a workaround for this. I think it would be something like this

loop through the keys of `node.attrs` and check if the `key` consist of space, if yes, split the key with space, suppose you got an array name `arr`

the original attribute key will be at `arr[arr.lenght - 1]`  whose value is the original value (`node.attrs[attr]`). 

change the `arr` with  `arr.slice(0,-1)` and all these values have `Boolean` `true` as their value cause 

`<a enable ></a>`  ↔️ `<a enable=true></a>`

so create a new attr object and loop through this `arr` and create the new `attr` object with values as `true` and prepend it to `node.attrs`


*This is kind of weird workaround but it will work*

**Comment by chimurai** [comment]
I believe github introduced a 'transfer' functionality for issues.
Think only admins can transfer issues to other repos.

https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

**Comment by anikethsaha** [comment]
Yes, I am waiting for @Scrum  or @voischev thoughts on this before transferring

**Comment by Scrum** [comment]
Only in those repositories for which there are rights)) rights to `htmlparser2` we do not have

**Comment by chimurai** [comment]
Ah ok.

I can open an issue in htmlparser2 if you think this issue belongs there

**Comment by Scrum** [comment]
feel free

**Comment by chimurai** [comment]
Looks like non-breaking space (U+00A0) can be part of the attribute name.

https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

> Attributes have a name and a value. Attribute names must consist of one or more characters other than controls, U+0020 SPACE, U+0022 ("), U+0027 ('), U+003E (>), U+002F (/), U+003D (=), and noncharacters. In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of ASCII lower and ASCII upper alphas.

CSS behaves similarly when you have an attribute with non-breaking space:
https://jsfiddle.net/dzpqvx6r/
