### ISSUE TITLE
directives not making it through to parser

### ISSUE THREAD

**Issue by chaseadamsio** [posthtml/posthtml-parser#41]
I have a directive in my call to `posthtml`:

```js
posthtml([transformer]).process(
      fs.readFileSync(filename).toString(),
      {
        directives: [{ name: "njk", start: "{{%", end: "%}}" }]
      }
    )
```

I noticed that the directive doesn't make it through to the parser and found that `last` here is `undefined` so the loop returns early. Should the `return` be a `continue`? I don't understand the purpose of `bufArray` here, if it's necessary can someone help me understand what the right way to pass a directive through is?

https://github.com/posthtml/posthtml-parser/blob/009fe5a1bdb1c4aeab17aa6b0639c0f86fa8fe23/index.js#L49-L57

**Comment by Scrum** [comment]
@chaseadamsio Hi, can you lay out or describe more criteria for reproducing this?

**Comment by Scrum** [comment]
i create test for you description https://github.com/posthtml/posthtml-parser/pull/42
