### ISSUE TITLE
HTML entities are being converted unexpectedly

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-parser#51]
I've noticed that, starting with `0.5.1`, HTML entities are being converted. 

This is unexpected and in my case (Maizzle) breaks HTML emails.

For example, this:

```html
<p>&copy; 2020</p>
```

... is output as:

```html
<p>© 2020</p>
```

Here's another example:

```html
<div>&zwnj;</div>

<div>&nbsp;</div>
```

... results in:

```html
<div></div>

<div> </div>
```

These should stay as they are and should not be converted. Is there something users can do about it, or must it be handled in core?

**Comment by cossssmin** [comment]
Here's a screenshot from running these in the `parser.js` test from PostHTML:

![image](https://user-images.githubusercontent.com/1656595/97587214-d1ae0980-1a03-11eb-929a-6ed4ca510c20.png)

**Comment by Scrum** [comment]
related to https://github.com/fb55/htmlparser2/issues/630

**Comment by cossssmin** [comment]
Found the breaking change in https://github.com/fb55/htmlparser2/commit/8ac01e0ed0950883f021b063ba0507fbae52252e, `decodeEntities` is now `true` by default - disabling it works as before.

**Comment by Scrum** [comment]
Strange, but the documents say that by default `false` https://github.com/fb55/htmlparser2/wiki/Parser-options#option-decodeentities

**Comment by cossssmin** [comment]
Yes, they probably forgot to update it 🤷‍♂️

**Comment by fb55** [comment]
> Yes, they probably forgot to update it 🤷‍♂️

That's spot on, thanks for flagging :)
