### ISSUE TITLE
Self closing tags pass / in attribute value if value is unquoted

### ISSUE THREAD

**Issue by ImBoop** [posthtml/posthtml-parser#83]
Example:
```
parser.parse('<test example=value/>')
```
will return:
```js
[ { tag: 'test', attrs: { example: 'value/' } } ]
```

Expected behavior:

```js
 { tag: 'test', attrs: { example: 'value' } } ]
```

**Comment by fb55** [comment]
For HTML, this is in line with the HTML spec; see https://html.spec.whatwg.org/multipage/parsing.html#attribute-value-(unquoted)-state. For any value not listed (which includes `/`), the spec asks for the character to be appended to the attribute value.

It is very much open for debate of `htmlparser2`'s `recognizeSelfClosing` option should work here. Afaik self-closing tags have never been spec'ed with not quoted attribute values, so there is no source of truth for how this should behave. I am inclined to leave this as is.

**Comment by Scrum** [comment]
Fully support @fb55

**Comment by ImBoop** [comment]
Curious that the spec would lean this way but given it does, I can agree as well. Appreciate the time!
