### ISSUE TITLE
[fix]: IE® conditional comments

### ISSUE THREAD

**Issue by stevenvachon** [posthtml/posthtml-parser#9]
Downlevel-hidden, -revealed and bubbling, so that we can correctly parse this:

``` js
<html>
<!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
<!--[if IE 7]><html class="no-js ie7"><![endif]-->
<!--[if IE 8]><html class="no-js ie8"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
```

_(Not that I condone writing such filth)_

**Comment by GitScrum** [comment]
Hi @stevenvachon thi related to:
- [ ] [Add support for condtional comment](https://github.com/fb55/htmlparser2/pull/146)

I hope that you no longer use such constructions

**Comment by stevenvachon** [comment]
@GitScrum cnn.com does

**Comment by GitScrum** [comment]
@stevenvachon i did not see there `Downlevel-hidden, -revealed and bubbling`

**Comment by SukkaW** [comment]
Although it is possible to extract the content of the conditional comment and pass it back to `postHtmlParser()` again (just as I did in https://github.com/posthtml/htmlnano/pull/119), however, the code snippet provided only has `<html>` start tag wrapped in a conditional comment, `posthtml-render` later will have to determine if `</html>` should be added. In https://github.com/posthtml/htmlnano/pull/125 I have to manually remove `</html>` from `result.html` (kind of a dirty hack).

**Comment by Scrum** [comment]
I thought the same, but it's very dirty

**Comment by Scrum** [comment]
I think that it makes no sense to invest a resource in supporting something that is no longer supported.

Feel free to reopen the issue if you think it's a high priority and a must for you.
